#pragma once

enum LButtonSprite {
    BUTTON_SPRITE_MOUSE_OUT,
    BUTTON_SPRITE_MOUSE_OVER_MOTION,
    BUTTON_SPRITE_MOUSE_DOWN,
    BUTTON_SPRITE_MOUSE_UP,
    BUTTON_SPRITE_TOTAL
};

enum KButton {
    BUTTON_SPRITE_UP,
    BUTTON_SPRITE_DOWN,
    BUTTON_SPRITE_LEFT,
    BUTTON_SPRITE_RIGHT,
    BUTTON_SPRITE_DEFAULT
};